sonar.projectKey=rameshwar-dudhe_sonarqube-python-demo
sonar.organization=rameshwar-dudhe
sonar.projectName=Demo Python Project
sonar.sources=.
sonar.exclusions=**/venv/**,**/*.html,**/*.json,generate_report.py
sonar.sourceEncoding=UTF-8
sonar.python.version=3
